const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();const initData=tg?.initData||'';const $=id=>document.getElementById(id);
const mineLevels=[{id:'easy',n:'Лёгкая',i:'🟢',w:9,h:9,m:10,r:250},{id:'medium',n:'Средняя',i:'🟡',w:16,h:16,m:40,r:1000},{id:'hard',n:'Сложная',i:'🔴',w:24,h:16,m:80,r:2500},{id:'insane',n:'Безумная',i:'💀',w:30,h:20,m:150,r:6000}];
const snakeLevels=[{id:'easy',n:'Лёгкая',i:'🟢',w:10,h:10,c:10},{id:'medium',n:'Средняя',i:'🟡',w:15,h:15,c:25},{id:'hard',n:'Сложная',i:'🔴',w:20,h:16,c:50},{id:'insane',n:'Безумная',i:'💀',w:26,h:20,c:100}];
let game=null,timer=null,startedAt=0,currentGame='',mineMode='open',snakeTimer=null,snakeWantedDirection='right',musicOn=localStorage.getItem('nya_music')==='1',musicTrack=Number(localStorage.getItem('nya_music_track')||0),rewardToken=null,reactionStart=0,reactionDone=false,targetScore=0,targetEnd=0,targetTimer=null;
function show(id,title,back=true){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');$('title').textContent=title;$('back').classList.toggle('hidden',!back)}
async function api(path,body={}){if(!initData)throw new Error('Открой мини-игры именно внутри Telegram через кнопку бота.');let r;try{r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Telegram-Init-Data':initData},body:JSON.stringify(body)})}catch(e){throw new Error('Сервер мини-игр недоступен. Попробуй открыть приложение заново.')}let d;try{d=await r.json()}catch(e){throw new Error('Сервер вернул некорректный ответ.')}if(!r.ok||!d.ok)throw new Error(d.error||'Ошибка');return d}
async function rewardGame(token,game,score,reward){try{return await api('/api/minigames/reward',{token,game,score,reward})}catch(e){$('result').textContent='⚠️ Награда не начислена: '+e.message;return null}}
async function startRewardSession(game){const x=await api('/api/minigames/start',{game});rewardToken=x.token;return x}
function renderLevels(){const arr=currentGame==='mines'?mineLevels:snakeLevels;$('difficultyHint').textContent=currentGame==='mines'?'Больше поле → больше риск → больше 🪙':'Больше поле → больше возможностей → больше 🪙';$('levels').innerHTML=arr.map(x=>`<button class="level" data-id="${x.id}"><span class="badge">${x.i}</span><span><b>${x.n}</b><small>${x.w}×${x.h}${currentGame==='mines'?` · ${x.m} мин`:` · ${x.c} 🪙 за яблоко`}</small></span><span class="money">💰 ${currentGame==='mines'?x.r.toLocaleString('ru-RU'):`+${x.c}`}</span></button>`).join('');document.querySelectorAll('.level').forEach(b=>b.onclick=()=>currentGame==='mines'?startMines(b.dataset.id):startSnake(b.dataset.id))}
async function startMines(d){try{currentGame='mines';const x=await api('/api/mines/start',{difficulty:d});game=x;startedAt=Date.now();$('mineControls').classList.remove('hidden');$('snakeControls').classList.add('hidden');$('reactionArea').classList.add('hidden');$('targetArea').classList.add('hidden');$('stat1').classList.remove('hidden');$('minesLeft').textContent=x.mines;$('reward').textContent=x.reward.toLocaleString('ru-RU');$('result').textContent='';clearInterval(timer);timer=setInterval(()=>$('timer').textContent=Math.floor((Date.now()-startedAt)/1000),1000);$('timer').textContent='0';renderMines();show('game','💣 Сапёр')}catch(e){alert(e.message)}}
function renderMines(){const size=Math.max(20,Math.min(36,Math.floor((innerWidth-45)/game.width)));$('board').style.gridTemplateColumns=`repeat(${game.width},${size}px)`;$('board').innerHTML=game.cells.map((v,i)=>{let t=v==='flag'?'🚩':v==='mine'?'💣':v===null?'':v||'';return `<button class="cell ${v!==null?'open':''} ${v==='mine'?'mine':''} ${v==='flag'?'flag':''}" style="width:${size}px;height:${size}px;font-size:${Math.max(11,size*.48)}px" data-i="${i}">${t}</button>`}).join('');document.querySelectorAll('.cell').forEach(b=>{b.onclick=()=>moveMine(+b.dataset.i,mineMode);b.oncontextmenu=e=>{e.preventDefault();moveMine(+b.dataset.i,'flag')}})}
async function moveMine(cell,action){if(!game||game.finished)return;try{game=Object.assign(game,await api('/api/mines/move',{game_id:game.game_id,cell,action}));$('minesLeft').textContent=game.mines-game.flags;renderMines();if(game.finished){clearInterval(timer);$('result').innerHTML=game.won?`🎉 <span class="win">Победа! +${game.reward.toLocaleString('ru-RU')} 🪙</span>`:'💥 <span class="lose">Мина! Попробуй ещё раз.</span>'}}catch(e){alert(e.message)}}
async function startSnake(d){try{currentGame='snake';const x=await api('/api/snake/start',{difficulty:d});game=x;$('mineControls').classList.add('hidden');$('snakeControls').classList.remove('hidden');$('reactionArea').classList.add('hidden');$('targetArea').classList.add('hidden');$('stat1').classList.remove('hidden');$('stat1').innerHTML='🍎 <b id="snakeScore">0</b>';$('reward').textContent='0';$('result').textContent='';renderSnake();show('game','🐍 Змейка');snakeWantedDirection='right';clearInterval(snakeTimer);snakeTimer=setInterval(()=>moveSnake(snakeWantedDirection),280)}catch(e){alert(e.message)}}
function renderSnake(){const size=Math.max(16,Math.min(30,Math.floor((innerWidth-35)/game.width)));$('board').style.gridTemplateColumns=`repeat(${game.width},${size}px)`;const body=new Set(game.snake);$('board').innerHTML=Array.from({length:game.width*game.height},(_,i)=>{let cls='cell snakecell',t='';if(i===game.food){t='🍎';cls+=' food'}else if(i===game.snake[0]){t='🐍';cls+=' snakehead'}else if(body.has(i)){t='🟢';cls+=' snakebody'}return `<div class="${cls}" style="width:${size}px;height:${size}px;font-size:${Math.max(10,size*.55)}px">${t}</div>`}).join('');$('reward').textContent=(game.reward||0).toLocaleString('ru-RU');$('snakeScore').textContent=game.score||0}
async function moveSnake(dir){if(!game||game.finished)return;snakeWantedDirection=dir;try{const x=await api('/api/snake/move',{game_id:game.game_id,direction:dir});game=x;renderSnake();if(game.finished){clearInterval(snakeTimer);$('result').innerHTML=game.score?`🐍 Игра окончена! Съедено: <b>${game.score}</b> 🍎 — получено <span class="win">+${game.reward.toLocaleString('ru-RU')} 🪙</span>`:'💥 Змейка врезалась! Попробуй ещё раз.'}}catch(e){clearInterval(snakeTimer);alert(e.message)}}
async function start2048(){currentGame='2048';try{await startRewardSession('2048')}catch(e){alert(e.message);return}game={size:4,tiles:Array(16).fill(0),score:0,finished:false};add2048();add2048();$('mineControls').classList.add('hidden');$('snakeControls').classList.add('hidden');$('reactionArea').classList.add('hidden');$('targetArea').classList.add('hidden');$('stat1').innerHTML='🏆 <b id="gameScore">0</b>';$('stat2').innerHTML='';$('stat3').innerHTML='💰 <b id="reward">0</b>';$('result').textContent='';show('game','🧱 2048');render2048()}
function add2048(){const f=game.tiles.map((v,i)=>v?null:i).filter(x=>x!==null);if(f.length)game.tiles[f[Math.floor(Math.random()*f.length)]]=Math.random()<.9?2:4}
function slide2048(row){let a=row.filter(Boolean);for(let i=0;i<a.length-1;i++)if(a[i]===a[i+1]){a[i]*=2;game.score+=a[i];a.splice(i+1,1)}while(a.length<4)a.push(0);return a}
function move2048(dir){if(game.finished)return;let old=game.tiles.slice(),grid=Array.from({length:4},(_,r)=>game.tiles.slice(r*4,r*4+4));if(dir==='left')grid=grid.map(slide2048);if(dir==='right')grid=grid.map(r=>slide2048(r.reverse()).reverse());if(dir==='up'||dir==='down'){for(let c=0;c<4;c++){let col=grid.map(r=>r[c]);if(dir==='down')col.reverse();col=slide2048(col);if(dir==='down')col.reverse();for(let r=0;r<4;r++)grid[r][c]=col[r]}}game.tiles=grid.flat();if(game.tiles.join()!=old.join()){add2048();render2048()}if(!can2048()){finish2048()}}
function can2048(){for(let i=0;i<16;i++){if(!game.tiles[i])return true;let x=i%4,y=Math.floor(i/4);if(x<3&&game.tiles[i]===game.tiles[i+1])return true;if(y<3&&game.tiles[i]===game.tiles[i+4])return true}return false}
async function finish2048(){if(game.finished)return;game.finished=true;const reward=Math.min(5000,Math.floor(game.score/10));const r=await rewardGame(rewardToken,'2048',game.score,reward);$('result').innerHTML=`🧱 Игра окончена. Счёт: <b>${game.score}</b> — ${r?`+${r.reward} 🪙`:''}`}
function render2048(){const colors={0:'',2:'2',4:'4',8:'8',16:'16',32:'32',64:'64',128:'128',256:'256',512:'512',1024:'1024',2048:'2048'};$('board').style.gridTemplateColumns='repeat(4,1fr)';$('board').innerHTML=game.tiles.map(v=>`<div class="tile t${colors[v]||''}">${v||''}</div>`).join('');$('gameScore').textContent=game.score;$('reward').textContent=Math.min(5000,Math.floor(game.score/10))}
async function startReaction(){currentGame='reaction';try{await startRewardSession('reaction')}catch(e){alert(e.message);return}$('mineControls').classList.add('hidden');$('snakeControls').classList.add('hidden');$('targetArea').classList.add('hidden');$('board').innerHTML='';$('stat1').innerHTML='⚡';$('stat2').innerHTML='';$('stat3').innerHTML='💰 <b id="reward">0</b>';$('reactionArea').classList.remove('hidden');$('reactionButton').className='wait';$('reactionButton').textContent='ЖДИ...';$('result').textContent='';show('game','⚡ Реакция');reactionDone=false;setTimeout(()=>{if(!reactionDone){reactionStart=performance.now();$('reactionButton').className='go';$('reactionButton').textContent='НАЖМИ!'}},1200+Math.random()*2500)}
$('reactionButton').onclick=async()=>{if(reactionDone)return;if(!reactionStart){$('reactionButton').textContent='Рано! 😼';setTimeout(()=>{$('reactionButton').textContent='ЖДИ...'},500);return}reactionDone=true;const ms=Math.max(0,Math.round(performance.now()-reactionStart));const r=await rewardGame(rewardToken,'reaction',ms,0);$('result').innerHTML=`⚡ ${ms} мс — ${r?`+${r.reward} 🪙`:'без награды'}`;if(!r)$('reactionButton').textContent='ГОТОВО'}
async function startTarget(){currentGame='target';try{await startRewardSession('target')}catch(e){alert(e.message);return}targetScore=0;targetEnd=Date.now()+30000;$('mineControls').classList.add('hidden');$('snakeControls').classList.add('hidden');$('reactionArea').classList.add('hidden');$('targetArea').classList.remove('hidden');$('stat1').innerHTML='🎯 <b id="targetScore">0</b>';$('stat2').innerHTML='⏱ <b id="targetTime">30</b>';$('stat3').innerHTML='💰 <b id="reward">0</b>';$('result').textContent='';show('game','🎯 Тир');spawnTarget();clearInterval(targetTimer);targetTimer=setInterval(()=>{let left=Math.max(0,targetEnd-Date.now());$('targetTime').textContent=Math.ceil(left/1000);if(!left)finishTarget()},100)}
function spawnTarget(){if(Date.now()>=targetEnd)return finishTarget();const f=$('targetField'),x=Math.random()*(f.clientWidth-58),y=Math.random()*(f.clientHeight-58);f.innerHTML=`<button class="target" style="left:${x}px;top:${y}px">🎯</button>`;f.firstChild.onclick=()=>{targetScore++;$('targetScore').textContent=targetScore;spawnTarget()}}
async function finishTarget(){if(!targetTimer)return;clearInterval(targetTimer);targetTimer=null;const reward=Math.min(1500,targetScore*15),r=await rewardGame(rewardToken,'target',targetScore,reward);$('targetField').innerHTML='';$('result').innerHTML=`🎯 Попаданий: <b>${targetScore}</b> — ${r?`+${r.reward} 🪙`:''}`}
async function showRecords(){show('records','🏆 Мои рекорды');$('recordsList').innerHTML='<div class="hint">Загружаю рекорды…</div>';try{const r=await fetch('/api/minigames/records',{headers:{'X-Telegram-Init-Data':initData}});const d=await r.json();if(!d.ok)throw Error(d.error);const names={mines:'💣 Сапёр',snake:'🐍 Змейка','2048':'🧱 2048',reaction:'⚡ Реакция',target:'🎯 Тир'};$('recordsList').innerHTML=Object.keys(names).map(k=>`<div class="record"><b>${names[k]}</b><span>${d.records[k]?.score||0}</span></div>`).join('')}catch(e){$('recordsList').innerHTML='<div class="hint">Рекорды появятся после первой игры.</div>'}}
$('digMode').onclick=()=>{mineMode='open';$('digMode').classList.add('active');$('flagMode').classList.remove('active')};$('flagMode').onclick=()=>{mineMode='flag';$('flagMode').classList.add('active');$('digMode').classList.remove('active')};document.querySelectorAll('.snake-controls button').forEach(b=>b.onclick=()=>moveSnake(b.dataset.dir));document.addEventListener('keydown',e=>{if(currentGame==='snake'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){const m={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'};if(m[e.key]){e.preventDefault();moveSnake(m[e.key])}}if(currentGame==='2048'){const m={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'};if(m[e.key]){e.preventDefault();move2048(m[e.key])}}});
let swipeStartX=0,swipeStartY=0;document.addEventListener('touchstart',e=>{if(currentGame==='2048'&&e.touches[0]){swipeStartX=e.touches[0].clientX;swipeStartY=e.touches[0].clientY}},{passive:true});document.addEventListener('touchend',e=>{if(currentGame!=='2048'||!e.changedTouches[0])return;const dx=e.changedTouches[0].clientX-swipeStartX,dy=e.changedTouches[0].clientY-swipeStartY;if(Math.max(Math.abs(dx),Math.abs(dy))<30)return;if(Math.abs(dx)>Math.abs(dy))move2048(dx>0?'right':'left');else move2048(dy>0?'down':'up')},{passive:true});
$('openMines').onclick=()=>{currentGame='mines';renderLevels();show('difficulty','💣 Сапёр')};$('openSnake').onclick=()=>{currentGame='snake';renderLevels();show('difficulty','🐍 Змейка')};$('open2048').onclick=start2048;$('openReaction').onclick=startReaction;$('openTarget').onclick=startTarget;$('openRecords').onclick=showRecords;$('newGame').onclick=()=>{if(currentGame==='2048')start2048();else if(currentGame==='reaction')startReaction();else if(currentGame==='target')startTarget();else{renderLevels();show('difficulty',currentGame==='mines'?'💣 Сапёр':'🐍 Змейка')}};$('back').onclick=()=>{$('game').classList.contains('hidden')?($('records').classList.contains('hidden')?show('games','🎮 Мини-игры',false):show('games','🎮 Мини-игры',false)):show(currentGame==='2048'||currentGame==='reaction'||currentGame==='target'?'games':'difficulty',currentGame==='mines'?'💣 Сапёр':currentGame==='snake'?'🐍 Змейка':'🎮 Мини-игры')};
const audio=$('bgMusic');audio.volume=.35;
const musicTracks=[['🌃 Розмова з містом — Nikow',0],['🌆 Moog City 2',1],['💗 DokiDoki — YOU DAYEON',2],['🌙 When You Find Me — plenka',3]];
function setMusicTrack(i,auto=true){musicTrack=Number(i)||0;localStorage.setItem('nya_music_track',musicTrack);audio.src='/api/music?track='+musicTrack; if(auto&&musicOn)audio.play().catch(()=>{});document.querySelectorAll('.music-option').forEach((b,n)=>b.classList.toggle('active',n===musicTrack));}
function renderMusic(){ $('musicList').innerHTML=musicTracks.map((x,i)=>`<button class="music-option ${i===musicTrack?'active':''}" data-track="${i}">${x[0]}${i===musicTrack?' ✓':''}</button>`).join('');document.querySelectorAll('.music-option').forEach(b=>b.onclick=()=>{setMusicTrack(b.dataset.track);$('musicPanel').classList.add('hidden')});}
function updateMusic(){ $('musicToggle').textContent=musicOn?'🔊':'🔇';if(musicOn){setMusicTrack(musicTrack);audio.play().catch(()=>{})}else audio.pause()}
$('musicToggle').onclick=()=>{musicOn=!musicOn;localStorage.setItem('nya_music',musicOn?'1':'0');updateMusic()};$('musicSelectBtn').onclick=()=>{$('musicPanel').classList.toggle('hidden');renderMusic()};document.addEventListener('click',e=>{if(musicOn&&e.target.closest('button')&&audio.paused)audio.play().catch(()=>{})});setMusicTrack(musicTrack,false);updateMusic();
async function showProfile(){show('profile','👤 Профиль');$('profileBox').innerHTML='<div class="hint">Загрузка…</div>';try{const r=await fetch('/api/minigames/profile',{headers:{'X-Telegram-Init-Data':initData}}),d=await r.json();if(!d.ok)throw Error(d.error);$('profileBox').innerHTML=`<div class="profile-name">👤 ${d.profile.name}</div><div class="profile-stat">🪙 Баланс <b>${d.profile.balance.toLocaleString('ru-RU')}</b></div><div class="profile-stat">⭐ Уровень <b>${d.profile.level}</b></div><div class="xpbar"><div style="width:${Math.min(100,Math.round((d.profile.exp/(d.profile.next_exp||1))*100))}%"></div></div><div class="hint">${d.profile.exp} / ${d.profile.next_exp} XP · 🔥 Стрик ${d.profile.streak}</div>`}catch(e){$('profileBox').innerHTML='<div class="hint">Не удалось загрузить профиль.</div>'}}
async function showLeaderboard(){show('leaderboard','🏆 Рейтинг');$('leaderboardList').innerHTML='<div class="hint">Загрузка…</div>';try{const r=await fetch('/api/minigames/leaderboard',{headers:{'X-Telegram-Init-Data':initData}}),d=await r.json();if(!d.ok)throw Error(d.error);$('leaderboardList').innerHTML=d.rows.map((x,i)=>`<div class="record"><b>${i+1}. ${x.name}</b><span>🪙 ${x.balance.toLocaleString('ru-RU')}</span></div>`).join('')||'<div class="hint">Пока никого нет.</div>'}catch(e){$('leaderboardList').innerHTML='<div class="hint">Рейтинг недоступен.</div>'}}
async function showDaily(){show('daily','🎁 Ежедневный бонус');$('dailyBox').innerHTML='<div class="hint">Бонус можно получать раз в 24 часа.<br>Стрик увеличивает награду.</div>';}
$('claimDaily').onclick=async()=>{try{const d=await api('/api/minigames/daily',{});$('dailyBox').innerHTML=`<div class="daily-reward">🎉 +${d.reward} 🪙</div><div class="hint">🔥 Серия: ${d.streak} дней</div>`;$('claimDaily').disabled=true}catch(e){$('dailyBox').innerHTML=`<div class="hint">${e.message}</div>`;$('claimDaily').disabled=true}}
async function showQuests(){show('quests','📋 Задания');$('questsList').innerHTML='<div class="hint">Загрузка…</div>';try{const r=await fetch('/api/minigames/quests',{headers:{'X-Telegram-Init-Data':initData}}),d=await r.json();$('questsList').innerHTML=d.tasks.map(t=>`<div class="record"><span><b>${t.claimed?'✅':'🔄'} ${t.description}</b><small>${t.progress}/${t.target} · +${t.reward} 🪙</small></span></div>`).join('')}catch(e){$('questsList').innerHTML='<div class="hint">Задания недоступны.</div>'}}
$('openProfile').onclick=showProfile;$('openLeaderboard').onclick=showLeaderboard;$('openDaily').onclick=showDaily;$('openQuests').onclick=showQuests;
show('games','🎮 Мини-игры',false);
