const tg=window.Telegram?.WebApp; tg?.ready(); tg?.expand();
const screen=document.getElementById('screen'), balance=document.getElementById('balance');
const state={tab:'home',profile:null,settings:{music:true,sound:true,vibrate:true},audio:null,game:null};
const initData=tg?.initData||'';
async function api(path,data={}){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,initData})});return r.json()}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function load(){const r=await api('/api/mini/profile');if(r.ok){state.profile=r;balance.textContent=`🪙 ${r.balance.toLocaleString()}`;}render()}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab)); if(state.tab==='home')home();else if(state.tab==='games')games();else if(state.tab==='rating')rating();else profile()}
function home(){const p=state.profile||{};screen.innerHTML=`<section class="hero"><h1>😼 Привет, ${esc(p.user?.name||'игрок')}!</h1><div class="muted">Твоя компактная панель Nya</div><div class="grid" style="margin-top:12px"><div class="stat">🪙<b>${(p.balance||0).toLocaleString()}</b><span class="muted">коинов</span></div><div class="stat">⭐<b>${p.stars||0}</b><span class="muted">Stars</span></div></div></section><section class="card"><div class="row"><b>⭐ Уровень ${p.level||1}</b><span>${p.exp||0}/${p.next_exp||0} XP</span></div><div class="progress"><i style="width:${Math.min(100,(p.exp||0)/(p.next_exp||1)*100)}%"></i></div></section><section class="card"><h2>🎁 Сегодня</h2><div class="muted">Ежедневный бонус с серией дней</div><button class="btn" id="bonus">Забрать бонус</button></section><section class="card"><h2>⚡ Быстрый доступ</h2><div class="grid"><button class="btn secondary" onclick="tab('games')">🎮 Играть</button><button class="btn secondary" onclick="tab('profile')">👤 Профиль</button></div></section>`;document.getElementById('bonus').onclick=claimBonus}
function games(){screen.innerHTML=`<section class="hero"><h1>🎮 Игры</h1><div class="muted">Игровые результаты и награды сохраняются в аккаунте.</div></section><div class="game-grid"><div class="game-card" onclick="mines()"><div class="ico">💣</div><b>Сапёр</b><span class="muted small">Классика</span></div><div class="game-card" onclick="snake()"><div class="ico">🐍</div><b>Змейка</b><span class="muted small">Управление без рывков</span></div><div class="game-card" onclick="game2048()"><div class="ico">🔢</div><b>2048</b><span class="muted small">Собери 2048</span></div><div class="game-card" onclick="reaction()"><div class="ico">⚡</div><b>Реакция</b><span class="muted small">Поймай момент</span></div><div class="game-card" onclick="shooter()"><div class="ico">🎯</div><b>Тир</b><span class="muted small">Попади по мишеням</span></div><div class="game-card" onclick="settings()"><div class="ico">⚙️</div><b>Настройки</b><span class="muted small">Музыка и эффекты</span></div></div>`}
async function rating(){const r=await api('/api/mini/leaderboard');screen.innerHTML=`<section class="hero"><h1>🏆 Рейтинг</h1><div class="muted">По XP аккаунта</div></section><section class="card"><ol class="list">${(r.rows||[]).map((x,i)=>`<li class="rank"><b>${i+1}</b><span>${esc(x.name)}<br><small class="muted">${x.level} LVL · ${x.exp} XP</small></span><b>${x.balance.toLocaleString()} 🪙</b></li>`).join('')}</ol></section>`}
function profile(){const p=state.profile||{};screen.innerHTML=`<section class="hero"><h1>👤 ${esc(p.user?.name||'Профиль')}</h1><div class="muted">Уровень ${p.level||1} · ${p.exp||0} XP</div></section><section class="card"><h2>📊 Активность</h2><div class="grid"><div class="stat"><b>${p.activity?.day||0}</b><span class="muted">день</span></div><div class="stat"><b>${p.activity?.week||0}</b><span class="muted">неделя</span></div><div class="stat"><b>${p.activity?.month||0}</b><span class="muted">месяц</span></div><div class="stat"><b>${p.activity?.all||0}</b><span class="muted">всё время</span></div></div></section><section class="card"><h2>🏅 Достижения</h2><p>${p.achievements||0} открыто</p><p class="muted">🎮 Игр: ${p.games_played||0} · 🏆 побед: ${p.game_wins||0}</p></section><section class="card"><h2>⚙️ Настройки</h2><button class="btn secondary" onclick="settings()">Открыть настройки Mini App</button></section>`}
async function claimBonus(){const b=document.getElementById('bonus');b.disabled=true;const r=await api('/api/mini/bonus');if(r.ok){tg?.showAlert(`🎁 +${r.reward} 🪙\n🔥 Серия: ${r.streak} дн.`);await load()}else tg?.showAlert(r.error==='already_claimed'?'🎁 Бонус уже забран сегодня.':'❌ Не удалось забрать бонус.');b.disabled=false}
async function startGame(name){const r=await api('/api/mini/game/start',{game:name});if(!r.ok){tg?.showAlert('❌ Не удалось запустить игру');return null}return r.game_id}
async function finishGame(id,score){const r=await api('/api/mini/game/finish',{game_id:id,score});if(r.ok){if(r.reward)tg?.showAlert(`🏆 +${r.reward} 🪙`);await load()}else tg?.showAlert('❌ Результат не принят');return r}
function backGames(){state.tab='games';games()}
async function mines(){const id=await startGame('mines');if(!id)return;let n=9,m=10,opened=new Set(),flags=new Set(),first=true,bombs=new Set();function setup(safe){bombs=new Set();while(bombs.size<m){let x=Math.floor(Math.random()*n*n);if(x!==safe)bombs.add(x)}}function neigh(x){let a=[];let r=Math.floor(x/n),c=x%n;for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){let rr=r+dr,cc=c+dc;if(rr>=0&&rr<n&&cc>=0&&cc<n)a.push(rr*n+cc)}return a}function count(x){return neigh(x).filter(v=>bombs.has(v)).length}function draw(msg=''){screen.innerHTML=`<section class="card mine-wrap"><div class="row"><h2>💣 Сапёр</h2><button class="btn secondary" onclick="backGames()">← Игры</button></div><p class="muted">Открывай клетки. Долгое нажатие ставит флаг.</p><div class="board" style="grid-template-columns:repeat(9,1fr)">${[...Array(81)].map((_,i)=>{let o=opened.has(i),f=flags.has(i);return `<button class="cell ${o?'open':''} ${bombs.has(i)&&o?'mine':''}" data-i="${i}">${f?'🚩':o?(bombs.has(i)?'💥':(count(i)||'')):''}</button>`}).join('')}</div><p>${msg}</p></section>`;document.querySelectorAll('.cell').forEach(b=>{let i=+b.dataset.i;b.onclick=()=>{if(flags.has(i))return;if(first){setup(i);first=false}if(bombs.has(i)){draw('💥 Мина!');finishGame(id,opened.size*10);return}opened.add(i);if(count(i)===0)neigh(i).forEach(v=>{if(!bombs.has(v))opened.add(v)});if(opened.size>=71){draw('🏆 Победа!');finishGame(id,opened.size*10);return}draw()};b.oncontextmenu=e=>{e.preventDefault();if(!opened.has(i)){flags.has(i)?flags.delete(i):flags.add(i);draw()}};b.ontouchstart=()=>{b._t=setTimeout(()=>{if(!opened.has(i)){flags.has(i)?flags.delete(i):flags.add(i);draw()}},500)};b.ontouchend=()=>clearTimeout(b._t)})}draw()}
async function snake(){const id=await startGame('snake');if(!id)return;let size=15,s=[[7,7]],food=[4,4],dir=[1,0],next=[1,0],score=0,running=true;function place(){food=[Math.floor(Math.random()*size),Math.floor(Math.random()*size)]}function draw(){screen.innerHTML=`<section class="card"><div class="row"><h2>🐍 Змейка</h2><button class="btn secondary" onclick="backGames()">← Игры</button></div><div class="snake">${s.map(p=>`<i class="dot" style="left:${p[0]*6.66}%;top:${p[1]*6.66}%"></i>`).join('')}<i class="dot food" style="left:${food[0]*6.66}%;top:${food[1]*6.66}%"></i></div><p>Счёт: <b>${score}</b></p><div class="pad"><span></span><button onclick="window.snakeTurn(0,-1)">⬆️</button><span></span><button onclick="window.snakeTurn(-1,0)">⬅️</button><button onclick="window.snakeTurn(0,1)">⬇️</button><button onclick="window.snakeTurn(1,0)">➡️</button></div></section>`}window.snakeTurn=(x,y)=>{if(x!==-dir[0]||y!==-dir[1])next=[x,y]};document.onkeydown=e=>{let k={'ArrowUp':[0,-1],'ArrowDown':[0,1],'ArrowLeft':[-1,0],'ArrowRight':[1,0]}[e.key];if(k)window.snakeTurn(...k)};draw();const timer=setInterval(()=>{if(!running){clearInterval(timer);return}dir=next;let h=[s[0][0]+dir[0],s[0][1]+dir[1]];if(h[0]<0||h[1]<0||h[0]>=size||h[1]>=size||s.some(p=>p[0]===h[0]&&p[1]===h[1])){running=false;draw();finishGame(id,score*100);return}s.unshift(h);if(h[0]===food[0]&&h[1]===food[1]){score++;place()}else s.pop();draw()},150)}
async function game2048(){const id=await startGame('2048');if(!id)return;let a=Array(16).fill(0),score=0;function add(){let z=a.map((v,i)=>v?null:i).filter(v=>v!==null);if(z.length)a[z[Math.floor(Math.random()*z.length)]]=Math.random()<.9?2:4}add();add();function move(dir){let before=a.join(',');let rows=[];for(let r=0;r<4;r++)rows.push(a.slice(r*4,r*4+4));if(dir==='up'||dir==='down')rows=Array.from({length:4},(_,c)=>rows.map(r=>r[c]));rows=rows.map(line=>{if(dir==='right'||dir==='down')line.reverse();line=line.filter(Boolean);for(let i=0;i<line.length-1;i++)if(line[i]===line[i+1]){line[i]*=2;score+=line[i];line.splice(i+1,1)}while(line.length<4)line.push(0);if(dir==='right'||dir==='down')line.reverse();return line});if(dir==='up'||dir==='down'){a=Array(16).fill(0);rows.forEach((r,c)=>r.forEach((v,i)=>a[i*4+c]=v))}else a=rows.flat();if(a.join(',')!==before)add();draw()}function draw(){screen.innerHTML=`<section class="card"><div class="row"><h2>🔢 2048</h2><button class="btn secondary" onclick="backGames()">← Игры</button></div><p>Счёт: <b>${score}</b></p><div class="tiles">${a.map(v=>`<div class="tile">${v||''}</div>`).join('')}</div></section>`}document.onkeydown=e=>{let d={'ArrowUp':'up','ArrowDown':'down','ArrowLeft':'left','ArrowRight':'right'}[e.key];if(d)move(d)};draw()}
async function reaction(){const id=await startGame('reaction');if(!id)return;let ready=false,t0=0;screen.innerHTML=`<section class="card"><div class="row"><h2>⚡ Реакция</h2><button class="btn secondary" onclick="backGames()">← Игры</button></div><div class="reaction" id="react">Жди зелёный сигнал...</div></section>`;const el=document.getElementById('react');let delay=1200+Math.random()*3000;setTimeout(()=>{ready=true;t0=performance.now();el.textContent='НАЖИМАЙ!';el.style.background='#295f4a'},delay);el.onclick=()=>{if(!ready){tg?.showAlert('Слишком рано 😼');return}let ms=Math.round(performance.now()-t0),score=Math.max(0,1200-ms);el.textContent=`${ms} мс`;finishGame(id,score)}}
async function shooter(){const id=await startGame('shooter');if(!id)return;let score=0,left=20;function draw(){screen.innerHTML=`<section class="card"><div class="row"><h2>🎯 Тир</h2><button class="btn secondary" onclick="backGames()">← Игры</button></div><p>Попыток: ${left} · Попаданий: ${score}</p><div class="reaction" id="target">🎯</div></section>`;document.getElementById('target').onclick=()=>{score++;left--;if(left<=0){draw();finishGame(id,score*100);return}draw()}}draw()}
function settings(){screen.innerHTML=`<section class="card settings"><h2>⚙️ Настройки Mini App</h2><label>🎵 Музыка <input id="music" type="checkbox" ${state.settings.music?'checked':''}></label><label>🔊 Звуки <input id="sound" type="checkbox" ${state.settings.sound?'checked':''}></label><label>📳 Вибрация <input id="vib" type="checkbox" ${state.settings.vibrate?'checked':''}></label><h3>🎵 Трек</h3><div class="grid"><button class="btn secondary" onclick="playMusic('city')">🏙 City</button><button class="btn secondary" onclick="playMusic('moog')">🌆 Moog</button><button class="btn secondary" onclick="playMusic('doki')">💗 DokiDoki</button><button class="btn secondary" onclick="playMusic('plenka')">🌌 Plenka</button></div><p class="muted small">Настройки хранятся на устройстве. Музыка загружается через сервер бота.</p></section>`;['music','sound','vib'].forEach(k=>document.getElementById(k).onchange=e=>state.settings[{music:'music',sound:'sound',vib:'vibrate'}[k]]=e.target.checked)}
async function playMusic(track='city'){if(state.audio){state.audio.pause();state.audio=null}state.audio=new Audio('/api/mini/music/'+track);state.audio.loop=true;state.audio.volume=.45;try{await state.audio.play()}catch{tg?.showAlert('Telegram/браузер заблокировал автозапуск. Нажми кнопку ещё раз.')}}
function tab(t){state.tab=t;render();if(t==='rating')rating()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));load();
